version: '3'

networks:
    laravel:

services:
    php:
        container_name: php_upload
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "9001:9000"
        volumes:
            - ./src:/code
        networks:
            - laravel
            
    nginx:
        container_name: nginx_upload
        image: nginx:alpine
        ports:
            - "8081:80"
        volumes:
            - ./src:/code
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - php